# Generated by Django 4.2 on 2023-04-08 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('pick_date', models.DateField()),
                ('pick_time', models.TimeField()),
                ('quantity', models.IntegerField()),
                ('wear_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('PANT', 'Pant'), ('SAREE', 'Saree'), ('TOWEL', 'Towel'), ('BED_SHEET', 'Bed Sheet'), ('BLANKET', 'Blanket'), ('CURTAIN', 'Curtain'), ('CARPET', 'Carpet'), ('OTHERS', 'Others')], max_length=100)),
                ('loundery_type', models.CharField(choices=[('WASH_IRON', 'Wash and Iron'), ('DRY_CLEAN', 'Dry Clean'), ('WASH', 'Wash'), ('IRON', 'Iron')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('PANT', 'Pant'), ('SAREE', 'Saree'), ('TOWEL', 'Towel'), ('BED_SHEET', 'Bed Sheet'), ('BLANKET', 'Blanket'), ('CURTAIN', 'Curtain'), ('CARPET', 'Carpet'), ('OTHERS', 'Others')], max_length=100)),
                ('loundery_type', models.CharField(choices=[('WASH_IRON', 'Wash and Iron'), ('DRY_CLEAN', 'Dry Clean'), ('WASH', 'Wash'), ('IRON', 'Iron')], max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=100)),
                ('laund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.laundry')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgot_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
